// permissions
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const TOGGLE_USER_STATUS = "TOGGLE_USER_STATUS";
export const SEND_USER_INFO = "SEND_USER_INFO";
export const SEND_LOCATION = "SEND_LOCATION";
export const SAVEOS = "SAVEOS";
export const GETDRIVES = "GETDRIVES";
export const SETLAUNCHERS = "SETLAUNCHERS";
export const SET_GAME_PATHS = "SET_GAME_PATHS";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const OPEN_GAME_MODEL = "OPEN_GAME_MODEL";
export const CLOSE_GAME_MODEL = "CLOSE_GAME_MODEL";
export const CHANGE_TITLE = "CHANGE_TITLE";
export const SET_GAME = "SET_GAME";
export const SET_PATH = "SET_PATH";
export const SET_NEW_PATH = "SET_NEW_PATH";
export const OPEN_ADD_GAME_MODEL = "OPEN_ADD_GAME_MODEL";
export const CLOSE_ADD_GAME_MODEL = "CLOSE_ADD_GAME_MODEL";
export const CONFIG_ADD_GAME = "CONFIG_ADD_GAME";
export const SET_CONFIG_FILE_PATH = "SET_CONFIG_FILE_PATH";
export const SET_BASE_CONFIG = "SET_BASE_CONFIG";
export const SET_CONFIG_GAMES = "SET_CONFIG_GAMES";
export const CHANGE_CONFIG_GAME_PATH = "CHANGE_CONFIG_GAME_PATH";
export const SET_IMAGE = "SET_IMAGE";
export const SET_IMAGE_CONFIG_PATH = "SET_IMAGE_CONFIG_PATH";
export const ADD_NEW_GAME = "ADD_NEW_GAME";
export const SET_NEW_GAME_PATH = "SET_NEW_GAME_PATH";


// settings
export const CHANGE_RATE = 'CHANGE_RATE';
