// permissions
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const SEND_USER_INFO = "SEND_USER_INFO";
export const SAVEOS = "SAVEOS";
export const GETDRIVES = "GETDRIVES";
export const SAVEAUTHKEY = "SAVEAUTHKEY";
export const SETLAUNCHERS = "SETLAUNCHERS";
export const SET_GAME_PATHS = "SET_GAME_PATHS";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const OPEN_GAME_MODEL = "OPEN_GAME_MODEL";
export const CLOSE_GAME_MODEL = "CLOSE_GAME_MODEL";
export const CHANGE_TITLE = "CHANGE_TITLE";
export const SET_GAME = "SET_GAME";
export const SET_PATH = "SET_PATH";
export const SET_NEW_PATH = "SET_NEW_PATH";
export const OPEN_ADD_GAME_MODEL = "OPEN_ADD_GAME_MODEL";
export const CLOSE_ADD_GAME_MODEL = "CLOSE_ADD_GAME_MODEL";
export const CONFIG_ADD_GAME = "CONFIG_ADD_GAME";
export const SET_CONFIG_FILE_PATH = "SET_CONFIG_FILE_PATH";
export const SET_BASE_CONFIG = "SET_BASE_CONFIG";
export const SET_CONFIG_GAMES = "SET_CONFIG_GAMES";
export const CHANGE_CONFIG_GAME_PATH = "CHANGE_CONFIG_GAME_PATH";
export const SET_IMAGE = "SET_IMAGE";
export const SET_IMAGE_CONFIG_PATH = "SET_IMAGE_CONFIG_PATH";
export const ADD_NEW_GAME = "ADD_NEW_GAME";
export const SET_NEW_GAME_PATH = "SET_NEW_GAME_PATH";
export const SET_MODIFY_IMAGE = "SET_MODIFY_IMAGE";
export const MAKE_MODIFIED = "MAKE_MODIFIED";
export const UN_MODIFIED = "UN_MODIFIED";
export const SAVE_CONFIG = "SAVE_CONFIG";
export const CONFIG_ADD_IMAGE_PATH = "CONFIG_ADD_IMAGE_PATH";
export const SET_CL_MAIN_FOLDER = "SET_CL_MAIN_FOLDER";
export const SET_CL_GAMES_FOLDER = "SET_CL_GAMES_FOLDER";
export const UPLOAD_FINISHED = "UPLOAD_FINISHED";
export const UPLOADING_GAMES = "UPLOADING_GAMES";
export const SET_CL_CONFIG_ID = "SET_CL_CONFIG_ID";
export const SET_CL_CONFIG = "SET_CL_CONFIG";
export const ADD_CL_GAMES = "ADD_CL_GAMES";
export const GAME_CHECK_COMPLETE = "GAME_CHECK_COMPLETE";
export const SET_TEMP_LOC_PATH = "SET_TEMP_LOC_PATH";
export const DOWNLOADING_SAVES = "DOWNLOADING_SAVES";
export const DOWNLOAD_FINISHED = "DOWNLOAD_FINISHED";

// settings
export const CHANGE_RATE = 'CHANGE_RATE';


export const UPLOADING = 'UPLOADING';
export const UPLOADING_SUCCESS = 'UPLOADING_SUCCESS';
export const UPLOADING_FAIL = 'UPLOADING_FAIL';